travis:
  secure:
    BINSTAR_TOKEN: ou2jHOz3no9DHZklmCQF9FLhRu8NT1oDPEmuvY8tViNGj054asJHunIf1pXEU9m6z7AGMd6EJVhHp/7xkSWs52OoK0Tc8i0cRm3f8Sjl5f8yw4U8f17mleTsWwWODz7Xle0GTP/mr1I1XwDsFRq7BBDCd4YXNMU8gh4lbPzjxcphf1qs2zLRiMxLUy3Mvnv03jwjMEW2jD28TrouIf9cj/g2V3i2kk/CbldOch9JyDdZkM/0fVEob/jevANxbyLE6HdRymUi3fUAS+egcM7ekL7VhuFBn6h5vGHz5IB1obR3DMEVQHvO2bMiMEfz0h8aZPh+azA0wyxR5swHqcyK7BffnTaDETjfObBI3+p5jBpW7lv8JvNjqpG32cLY5nRu8Tm9ZUhhCmVK89oJ7o74omJM65phdvuKZzOT9kJvM9vWR9UW0ErfFYaYgxXRyaWVgtFP/wLu2Zr/7wdnwGh11q/VPxSAFpUAZIMyVtAM1HAyKjuyUNPsy60WCM88rBAZDCaL3n4dHYqJuQtiueOCglb2tIhMy3kiVSW/xaMBHiENqdMfqZI9tro8VnoAfz8qCtJ5B71MVXsdfRu3o7l6yRZP2MVWOz0Y/Le0XFcbD3K9uD1i11BSAxtYP6Y2ehpdXHafS9EnveRdp89x+mlxFhW6rwHCduT3kpy/4nYdtxg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
