travis:
  secure:
    BINSTAR_TOKEN: medOcPSIJHr02lpMbxb6RsGijUfiS7VQ8Fh594h3Du0OPXWgcW6APg0WrWvZnjwWZj5VpDVQ5Fjwsa2dv+mnFprop1wYHmwtMplWWEH6Gd0dOGxaidyYKQJGbdxrpUeFsKqj94XYEIEFVAca74KyGVjR6XhpZcHm/q0MuTCbYakH3fqsEK75Ched0NK3i/f+/jh96P0lMrgfxChT7E1cjhc5qn1Bqi7JE2n9WLRI4mrYb0GL1v/9Mz8fUtUGfXj7faq7pFCvRlkU2kOJIM8z9NiO5IEmA/KkuHFLoRbuV6ub45X0U9/1Mya3uOexGjxPu6gFZGm5V63ce8g0D9iCY/CDRaio+ISJQ9YToJ4Amde1l8O1qxJ0wjBuPP7GJghW6A4AV3x6xw/4K1KfxemRTKxbZaZZSXOMeHuVepwlRlxdaiP76Rr3/u8j5L2LAvcgEoMpkf6YyivvvQl1SzSIDSLfRMGXUCZaNhf3Dn1jWpI0ky9nLoomYx9LHEEKdWMDdga8RYBySZVHEtDz3SQUPGzkwvpwgkNPMRwaPrPlmgX4K5TRJLmLvfNEUXdUs9fjcM83FP9wLVRjhI5QlWK94FQ9yx1i/rj+9/7Ucwetsq/+oYDFyn62pxFArLpUrG2NsNDGMpdPW68dS4ZsSyQCTF0LWYOxn/YKEMf/ymyxVwU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
